### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [HeeebsInc/FaceMaskEmotionDetection#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by HeeebsInc** [comment]
I appreciate your feedback!  I will add the license right now.  As I am a self-taught programmer, I often forget the importance of adding a license so again I really appreciate you telling me.

**Comment by HeeebsInc** [comment]
Just added it!
